# Generated by Django 4.1.3 on 2022-12-05 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_post', models.CharField(choices=[('Giving', 'Giving'), ('Taking', 'Taking')], max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('summ', models.IntegerField()),
                ('percent', models.IntegerField()),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('US', 'US'), ('KZ', 'KZ')], max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('term_of_conditions', models.IntegerField()),
                ('status', models.BooleanField(default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_order', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('IN ACTION', 'IN ACTION'), ('FINISHED', 'FINISHED'), ('CANCELED', 'CANCELED')], max_length=255, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.post')),
                ('user_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('user_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
