# Generated by Django 4.1.3 on 2022-12-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretinfo',
            name='number',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
